plugins {
    id "io.github.qishr.cascara-meta.java-library" version "0.1.0"
    id "io.github.qishr.cascara-meta.publish" version "0.1.0"
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("org.gradlex.extra-java-module-info") version "1.13.1"
}


repositories {
	mavenLocal()
	mavenCentral()
}


dependencies {
    implementation(platform("io.github.qishr:cascara-meta-bom:0.1.10"))

    // Cascara Dependencies
    implementation "io.github.qishr:cascara-common"
    implementation "io.github.qishr:cascara-common-io"
    implementation "io.github.qishr:cascara-lang-yaml"
    implementation "io.github.qishr:cascara-schema"
    implementation "io.github.qishr:cascara-ui"

    // MacOS Menus
    implementation 'de.jangassen:nsmenufx:3.1.0'
    implementation 'net.java.dev.jna:jna:5.7.0'
}


javafx {
    version = "25"
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.graphics' ]
}


extraJavaModuleInfo {
    failOnMissingModuleInfo = false
    failOnAutomaticModules = true
    skipLocalJars = true

    module("net.java.dev.jna:jna", "com.sun.jna") {
        patchRealModule();
        requires("java.logging")
        exportAllPackages();
    }

    module("net.java.dev.jna:jna-platform", "com.sun.jna.platform") {
        patchRealModule();
        exportAllPackages();
    }
}


// tasks.register('runtimeModulePath', Copy) {
//     dependsOn tasks.named('jar')
//     from configurations.runtimeClasspath
//     duplicatesStrategy = DuplicatesStrategy.EXCLUDE

//     exclude "jna-*-jpms.jar"
//     // exclude "jna-*-module.jar"

//     def modulePathDir = new File(rootProject.buildDir, 'modulepath')
//     modulePathDir.mkdirs()
//     into modulePathDir

//     doLast {
//         println "Finished copying files to modulepath."
//     }
// }


// tasks.named('build') {
//     finalizedBy(tasks.named('runtimeModulePath'))
// }




// jar {
//     archiveBaseName.set(maven_name)
//     manifest {
//         attributes( 'Implementation-Title': maven_name,
//                     'Implementation-Version': version,
//                     'Implementation-Vendor': group,
//                     'Automatic-Module-Name': java_name,
//                     'Build-Date': new Date())
//     }
// }


// jar.doLast {
//     def jarFile = archiveFile.get().asFile
//     ant.checksum file: jarFile
// }


// signing {
//     sign publishing.publications
// }


// publishing {
//     publications {
//         pub(MavenPublication) {
//             from components.java
//             pom {
//                 name = maven_name
//                 description = title
//                 url = "https://qishr.github.io/${maven_name}"
//                 licenses {
//                     license {
//                         name = "Apache License, Version 2.0"
//                         url = "https://www.apache.org/licenses/LICENSE-2.0"
//                     }
//                 }
//                 developers {
//                     developer {
//                         id = 'qishr'
//                         name = 'Sandy Dunlop'
//                         email = 'sandy.dunlop@gmail.com'
//                     }
//                 }
//                 scm {
//                     connection = "scm:git:git://github.com/qishr/${maven_name}.git"
//                     developerConnection = "scm:git:ssh://github.com:qishr/${maven_name}.git"
//                     url = "https://github.com/qishr/${maven_name}"
//                 }
//             }
//         }
//     }

// 	repositories {
//         maven {
//             name = "LocalMavenWithChecksums"
//             url = uri(layout.buildDirectory.dir("staging-deploy"))
//         }
//     }
// }
