version = 0.2.0
java_name = "cascara.macos.menus"
maven_name = "cascara-macos-menus"
group = io.github.qishr
title = "Cascara macOS Menus"
description = Cascara macOS system menu integration
url = https://qishr.github.io/javadoc/cascara.macos.menus/
scm_url = https://github.com/qishr/cascara-macos-menus
scm_conn = scm:git:https://github.com/qishr/cascara-macos-menus.git
scm_dev_conn = scm:git:https://github.com/qishr/cascara-macos-menus.git

org.gradle.configuration-cache = false
overrideLicense = 'MIT'


